#!/usr/bin/env python
# LIBTBX_SET_DISPATCHER_NAME diffBragg.make_phil
"""
Generate a diffBragg hopper phil configuration for rotation data.

Reads experiment geometry to set sensible defaults for Nabc, unit cell,
goniometer, and structure factors. Optionally estimates init.G by running
a quick G-only pre-refinement on a handful of frames.

Philosophy:
  - Nabc estimated from unit cell as ~1200/cell_i (domain ~1200 A)
  - B-factor free with lower bound at 1 (avoid B<0 artifacts)
  - Cholesky Nabc parameterization (always, for anisotropic domains)
  - no_Nabc_scale=True (break G*det(NABC) degeneracy)
  - space_group set from experiment (for proper ASU HKL in diagnostics)
  - save_spot_diagnostics=True (for post-refinement analysis)

Two-step workflow:
  Step 1: make_phil.py generates the phil
  Step 2: user runs hopper with the phil

For G estimation (--estimate-G):
  Runs hopper on ~5 frames with only G free (everything else fixed),
  using the generated phil. Extracts median refined G and rewrites
  the phil with the estimated G as init.

Usage:
  # Basic: generate phil from experiment + MTZ
  python make_phil.py --expt expanded/frame_000000.expt \\
                      --mtz iobs_all.mtz \\
                      --mtz-column "Iobs(+),SIGIobs(+),Iobs(-),SIGIobs(-)" \\
                      --delta-phi 0.1 \\
                      --outdir my_run \\
                      -o my_run.phil

  # With exp_ref_spec (for multi-frame runs):
  python make_phil.py --spec expanded/exp_ref_spec.txt \\
                      --mtz iobs_all.mtz \\
                      --delta-phi 0.1 \\
                      --outdir my_run \\
                      -o my_run.phil

  # With G estimation (requires simtbx environment):
  python make_phil.py --spec expanded/exp_ref_spec.txt \\
                      --mtz iobs_all.mtz \\
                      --delta-phi 0.1 \\
                      --outdir my_run \\
                      --estimate-G \\
                      -o my_run.phil
"""

from __future__ import division, print_function

import argparse
import os
import sys
import math


def read_experiment_info(expt_path):
    """Read unit cell, space group, wavelength from an experiment file."""
    from dxtbx.model import ExperimentList
    El = ExperimentList.from_file(expt_path, False)
    E = El[0]

    crystal = E.crystal
    uc = crystal.get_unit_cell().parameters()  # (a, b, c, alpha, beta, gamma)
    sg = crystal.get_space_group().info().type().lookup_symbol()

    beam = E.beam
    wavelength = beam.get_wavelength()

    # Check for goniometer
    gonio = E.goniometer
    if gonio is not None:
        axis = gonio.get_rotation_axis()
    else:
        axis = None

    # Check for scan
    scan = E.scan
    if scan is not None:
        osc = scan.get_oscillation()  # (start_angle, osc_width)
        n_images = scan.get_num_images()
    else:
        osc = None
        n_images = None

    return {
        "unit_cell": uc,
        "space_group": sg,
        "wavelength": wavelength,
        "gonio_axis": axis,
        "oscillation": osc,
        "n_images": n_images,
    }


def estimate_nabc(uc):
    """Estimate initial Nabc from unit cell dimensions.

    Uses domain size of ~1200 A as a starting point.
    N_i = round(domain_size / cell_i)
    """
    a, b, c = uc[0], uc[1], uc[2]
    domain_size = 1200.0  # Angstroms, reasonable for a well-diffracting crystal
    Na = max(5, round(domain_size / a))
    Nb = max(5, round(domain_size / b))
    Nc = max(5, round(domain_size / c))
    return int(Na), int(Nb), int(Nc)


def estimate_phi_steps(delta_phi):
    """Estimate number of phi steps for rotation integration.

    ~10 steps per 0.1 deg oscillation. Diminishing returns beyond 10.
    """
    steps_per_tenth = 10
    return max(5, min(20, int(round(steps_per_tenth * delta_phi / 0.1))))


def generate_phil(args, info, init_G=None):
    """Generate the phil configuration string."""
    uc = info["unit_cell"]
    sg = info["space_group"]
    Na, Nb, Nc = estimate_nabc(uc)
    phi_steps = estimate_phi_steps(args.delta_phi)

    G = init_G if init_G is not None else args.init_G

    lines = []
    lines.append("# Generated by make_phil.py")
    lines.append("# Unit cell: a=%.2f b=%.2f c=%.2f  alpha=%.1f beta=%.1f gamma=%.1f" % uc)
    lines.append("# Space group: %s" % sg)
    lines.append("# Wavelength: %.4f A" % info["wavelength"])
    lines.append("# Nabc estimated from ~1200 A domain size")
    if init_G is not None:
        lines.append("# G estimated from pre-refinement")
    lines.append("")

    # Output
    lines.append('outdir = "%s"' % args.outdir)

    # Input
    if args.spec:
        lines.append('exp_ref_spec_file = "%s"' % os.path.abspath(args.spec))
    elif args.expt and args.refl:
        lines.append('exp_ref_spec_file = "%s"' % os.path.abspath(args.spec_out))

    # Space group (critical for ASU HKL in diagnostics)
    lines.append('space_group = "%s"' % sg)

    # Optimizer
    lines.append('method = "L-BFGS-B"')

    # Debug and diagnostics
    if args.debug:
        lines.append("debug_mode = True")
    lines.append("save_spot_diagnostics = True")

    # Initialization
    lines.append("init {")
    lines.append("  Nabc = %d %d %d" % (Na, Nb, Nc))
    lines.append("  G = %.0f" % G)
    lines.append("  B = %d" % args.init_B)
    lines.append("}")

    # Bounds
    lines.append("mins {")
    lines.append("  cholesky = 0.1 -10 0.1 -10 -10 0.1")
    lines.append("  B = 1")
    lines.append("}")
    lines.append("maxs {")
    lines.append("  cholesky = 20 10 20 10 10 20")
    lines.append("  G = 1e+18")
    lines.append("}")

    # Free/fix parameters
    lines.append("fix {")
    lines.append("  B = False")
    if not args.fix_ucell:
        lines.append("  ucell = False")
    lines.append("}")

    # Cholesky and scale
    lines.append("no_Nabc_scale = True")
    lines.append("use_cholesky_Nabc = True")

    # Logging
    lines.append("logging {")
    lines.append("  rank0_level = low normal *high")
    lines.append("}")

    # Simulator
    lines.append("simulator {")
    lines.append("  gonio {")
    lines.append("    delta_phi = %.4f" % args.delta_phi)
    if info["gonio_axis"] is not None:
        ax = info["gonio_axis"]
        lines.append("    axis = %.4f,%.4f,%.4f" % (ax[0], ax[1], ax[2]))
    lines.append("    phi_steps = %d" % phi_steps)
    lines.append("  }")
    lines.append("  structure_factors {")
    lines.append('    mtz_name = "%s"' % os.path.abspath(args.mtz))
    lines.append('    mtz_column = "%s"' % args.mtz_column)
    lines.append("  }")
    lines.append("  detector {")
    lines.append("    force_zero_thickness = True")
    lines.append("  }")
    lines.append("}")

    # GPU
    if args.num_devices > 0:
        lines.append("refiner {")
        lines.append("  num_devices = %d" % args.num_devices)
        lines.append("}")

    # ROI
    if args.mask:
        lines.append("roi {")
        lines.append("  trusted_range = 0 100000")
        lines.append('  hotpixel_mask = "%s"' % os.path.abspath(args.mask))
        lines.append("}")

    return "\n".join(lines) + "\n"


def generate_g_estimation_phil(base_phil_str, n_frames=5):
    """Generate a phil for G-only pre-refinement.

    Fixes everything except G, runs on a small number of frames.
    """
    extra = """
# G-estimation mode: fix everything except G
fix {
  RotXYZ = True,True,True
  Nabc = True
  B = True
  ucell = True
  detz_shift = True
}
# Quick run: fewer iterations
method = "L-BFGS-B"
lbfgs_maxiter = 200
"""
    return base_phil_str + extra


def run_g_estimation(phil_path, spec_path, n_frames=5):
    """Run a quick G pre-estimation using hopper.

    Returns the estimated G value.
    """
    import subprocess
    import tempfile
    import glob

    # Create a temp spec file with only n_frames entries
    with open(spec_path) as f:
        all_lines = [l.strip() for l in f if l.strip()]

    # Sample evenly across the scan
    if len(all_lines) > n_frames:
        step = len(all_lines) // n_frames
        selected = [all_lines[i * step] for i in range(n_frames)]
    else:
        selected = all_lines

    tmpdir = tempfile.mkdtemp(prefix="g_est_")
    tmp_spec = os.path.join(tmpdir, "g_est_spec.txt")
    with open(tmp_spec, "w") as f:
        for line in selected:
            f.write(line + "\n")

    # Read the base phil and override spec + outdir
    with open(phil_path) as f:
        phil_str = f.read()

    g_phil_str = generate_g_estimation_phil(phil_str)
    g_phil_str = g_phil_str.replace(
        'exp_ref_spec_file = "%s"' % os.path.abspath(spec_path),
        'exp_ref_spec_file = "%s"' % tmp_spec)
    g_phil_str = g_phil_str.replace(
        'outdir = "', 'outdir = "%s/' % tmpdir.rstrip("/"))

    g_phil_path = os.path.join(tmpdir, "g_est.phil")
    with open(g_phil_path, "w") as f:
        f.write(g_phil_str)

    print("\n--- G ESTIMATION ---")
    print("Running hopper on %d frames with G-only refinement..." % len(selected))
    print("Temp dir: %s" % tmpdir)
    print("Phil: %s" % g_phil_path)

    # Run hopper via Python (dispatcher may not exist in conda envs)
    hopper_script = os.path.join(os.path.dirname(__file__), "hopper.py")
    cmd = [sys.executable, hopper_script, g_phil_path]
    print("Command: %s" % " ".join(cmd))
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)

    if result.returncode != 0:
        print("WARNING: G estimation failed (return code %d)" % result.returncode)
        print("STDERR:", result.stderr[-500:] if result.stderr else "")
        return None

    # Read refined G from shot summary CSVs
    import pandas as pd
    csv_files = glob.glob(os.path.join(tmpdir, "*/spot_diagnostics/rank*/*_shot_summary.csv"))
    if not csv_files:
        # Try the outdir pattern
        csv_files = glob.glob(os.path.join(tmpdir, "spot_diagnostics/rank*/*_shot_summary.csv"))

    if not csv_files:
        print("WARNING: No shot summary CSVs found after G estimation")
        return None

    dfs = [pd.read_csv(f) for f in csv_files]
    df = pd.concat(dfs, ignore_index=True)
    G_median = df["G"].median()
    G_mean = df["G"].mean()

    print("G estimation results (%d frames):" % len(df))
    print("  G median = %.2e" % G_median)
    print("  G mean   = %.2e" % G_mean)
    print("  G range  = %.2e to %.2e" % (df["G"].min(), df["G"].max()))
    print("Using median G = %.2e" % G_median)
    print("--- END G ESTIMATION ---\n")

    return G_median


def main():
    parser = argparse.ArgumentParser(
        description="Generate a diffBragg hopper phil for rotation data",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # From exp_ref_spec.txt (typical for expanded rotation data):
  python make_phil.py --spec expanded/exp_ref_spec.txt \\
      --mtz iobs_all.mtz --delta-phi 0.1 --outdir run1 -o run1.phil

  # Read crystal info from a specific experiment:
  python make_phil.py --expt expanded/frame_000000.expt \\
      --spec expanded/exp_ref_spec.txt \\
      --mtz iobs_all.mtz --delta-phi 0.1 --outdir run1 -o run1.phil

  # With G pre-estimation:
  python make_phil.py --spec expanded/exp_ref_spec.txt \\
      --mtz iobs_all.mtz --delta-phi 0.1 --outdir run1 \\
      --estimate-G -o run1.phil

  # Then run hopper:
  mpirun -n 12 simtbx.diffBragg.hopper run1.phil
""")
    parser.add_argument("--expt", help="Experiment file (.expt) to read crystal/beam info from. "
                        "If not given, reads first entry from --spec.")
    parser.add_argument("--refl", help="Reflection file (.refl) - only needed without --spec")
    parser.add_argument("--spec", help="exp_ref_spec.txt file listing expt/refl/spectrum triples")
    parser.add_argument("--mtz", required=True, help="MTZ file with structure factors")
    parser.add_argument("--mtz-column", default="Iobs(+),SIGIobs(+),Iobs(-),SIGIobs(-)",
                        help="MTZ column label(s)")
    parser.add_argument("--delta-phi", type=float, required=True,
                        help="Oscillation width per frame in degrees (e.g. 0.1)")
    parser.add_argument("--outdir", required=True, help="Output directory for hopper")
    parser.add_argument("-o", "--output", default="hopper.phil",
                        help="Output phil filename (default: hopper.phil)")
    parser.add_argument("--mask", default=None, help="Hotpixel mask file (.pkl)")
    parser.add_argument("--init-G", type=float, default=1e5,
                        help="Initial G scale factor (default: 1e5, use --estimate-G for auto)")
    parser.add_argument("--init-B", type=float, default=20,
                        help="Initial B-factor (default: 20)")
    parser.add_argument("--num-devices", type=int, default=0,
                        help="Number of GPU devices (0 = CPU only)")
    parser.add_argument("--debug", action="store_true",
                        help="Enable debug_mode (saves modeler .npy files, heavy output)")
    parser.add_argument("--fix-ucell", action="store_true",
                        help="Fix unit cell during refinement")
    parser.add_argument("--estimate-G", action="store_true",
                        help="Run a quick G-only pre-refinement on ~5 frames to estimate init.G")
    parser.add_argument("--g-est-frames", type=int, default=5,
                        help="Number of frames for G estimation (default: 5)")

    args = parser.parse_args()

    # Determine experiment file to read crystal info from
    expt_path = args.expt
    if expt_path is None and args.spec:
        # Read first entry from spec file
        with open(args.spec) as f:
            first_line = f.readline().strip()
        expt_path = first_line.split()[0]
        print("Reading crystal info from first spec entry: %s" % expt_path)

    if expt_path is None:
        print("ERROR: Need --expt or --spec to read crystal information")
        sys.exit(1)

    # Read experiment info
    print("Reading experiment: %s" % expt_path)
    info = read_experiment_info(expt_path)

    uc = info["unit_cell"]
    print("  Unit cell: a=%.2f b=%.2f c=%.2f  alpha=%.1f beta=%.1f gamma=%.1f" % uc)
    print("  Space group: %s" % info["space_group"])
    print("  Wavelength: %.4f A" % info["wavelength"])

    Na, Nb, Nc = estimate_nabc(uc)
    print("  Estimated Nabc: %d %d %d (domain ~1200 A)" % (Na, Nb, Nc))
    print("  Phi steps: %d (for delta_phi=%.3f deg)" % (
        estimate_phi_steps(args.delta_phi), args.delta_phi))

    # Generate phil
    init_G = None
    phil_str = generate_phil(args, info, init_G=init_G)

    # Write phil
    with open(args.output, "w") as f:
        f.write(phil_str)
    print("\nWrote phil to: %s" % args.output)

    # G estimation (optional, after writing initial phil)
    if args.estimate_G:
        if not args.spec:
            print("ERROR: --estimate-G requires --spec")
            sys.exit(1)
        G_est = run_g_estimation(args.output, args.spec, n_frames=args.g_est_frames)
        if G_est is not None:
            # Rewrite phil with estimated G
            phil_str = generate_phil(args, info, init_G=G_est)
            with open(args.output, "w") as f:
                f.write(phil_str)
            print("Updated phil with estimated G = %.2e" % G_est)
        else:
            print("WARNING: G estimation failed, keeping default G = %.0f" % args.init_G)

    # Print run instructions
    print("\n" + "=" * 60)
    print("TO RUN:")
    print("=" * 60)
    if args.num_devices > 0:
        print("  mpirun -n <NPROC> simtbx.diffBragg.hopper %s" % args.output)
    else:
        print("  mpirun -n <NPROC> simtbx.diffBragg.hopper %s" % args.output)
    print("")
    print("TO ANALYZE:")
    print("  python analyze/analyze_spots_by_resolution.py %s" % args.outdir)
    print("  python analyze/analyze_hkl_errors.py %s" % args.outdir)
    print("  python analyze/analyze_asu_rocking.py %s --space-group '%s'" % (
        args.outdir, info["space_group"]))
    print("  python analyze/analyze_temporal.py %s" % args.outdir)
    print("  python analyze/analyze_params.py %s" % args.outdir)


if __name__ == "__main__":
    main()
